language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: GIZwPgBcHuDlBl5vT6+xTN+U7PV7LJi2XE+NvjUu6V9i55I6nL9AGSWsJXonpo2HS/KjEIeiH0RzR/nXXnNvcAJ2CrtoGCphcePTYJJTzOMIl+9VorG2q35ft7PWAdHaejBDC4t0+6VsZykQZHGOjwaIOGS3GTPTZGZmLn4n2HIhXORD3zjIzdxLBXPd4TibHwPUGkBwTJ2puMF+NoSJylGW5UyJVAQQFnppv29nAPT9R0untvDsoGAn6uxeUWzH9tFVYzyofnbDeIqtH/G00ugvq/KVIwMRZozN4bAblg2Hj/jnUv2CWH2q1xZQOk6p3I+tHWDwGqAcc7MLwmSaQ4QnBHrwB3nq/rVfQUXjnCYMFzv3OUNOnTZ63XVAbXkqqAg6DzLseBM0QrsF2JadPbDsy2pSmCwYzishi28vlmtF547dx4Bxtyv+Mrmm4CC9zoWi04n/ONtGR6QL1CQDfzHtig9Wc1c1lsajqJUt5pk2vU4y98lH7GxlM05xjhJu9oNiDxdIdvZ9Ikw7ADIP57YuxVZMKuMb9jXCuiUf9EmO/yOg4M5HJD82vG1ikbmhfESsqwsUdtggrS4Dfc8Pq5RMCoqLzwNo3LtoA2/1FCz1CjKacTWYRvGQs1AyltXvKediePQbj2dzou4leD8UEIl2bzCdaR4Kq4zI9v3QINE=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: letHS5FGTHTEUN26uPGxxj3XVgbrH7pK6XPmFMQWX3CxcwzFUSiQGGFrQO+jE2BdDBfmNEwgbyDe1A1Jn5wt3bIQ2zK1Q0Tpt0gvlpNg/1N0OP+5qqVHyvEHwEA9bniOrXEXgFjGlakvE4agohxc5isjhJ9F3BcK+j0ECUNf2Mmo12zVdK+RAhpqd1+ScNNnSIPe0itjiw6LS36QXi9cb7rUjMYXJu4OwDvzw65ZXaolOhtiTLnJtKrwu5p/u4Cg2Vdf0PBAKFhqKQtTzOp2ssA47/svQc8wgvIMJ5sIrH+jKZZWOfrcZCquW6XlSrm+gp/2p6fSPmwOcLeNY0sJyWM71OMzwwLMbOq3YkKtBgc33BCWBvpkxAzkPXvSesRVkjKiekRAuwzDHnE2QtLwvtQ0duS3WPb8pYqr9RkWZZIHIUZ8h8hEGME8NzVOgU4mQeYJCV1LUh8hpmE7rZ8z1Zuk7ncGCVq1tQkdsBC0Fe45upTatVqle5pAhRvi1KiK7uUm8pjw3zKM0zXM6cU2SlwoviaW4EH1zPQh6pnYSskv3iMdLFVMYyBWqcGy9WM9DkI8hNifUXWbdfoSocYzShDIRLIvrnFBMlZSXJ7R2atzwpz6qzHBoX47JhewRXtToOFWMZt24OALexsd0zB2srGU6EQIlZHOcSuikLMH7bI=
sudo: false
