language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: FspU4CGk1l7VtbmBKokoASOxSjAtC7EatYxbqC85OhhXm55VsfgmV5L+sfR+AslMS9REsv7syX5SwUX2bNpF86R5UtCBXSyQzQUgs9B68TFSVDMathlu9F7BLcLg6VwiCbGP4W56d262MHXlkPjx/38tFTQww08ovdMmI77a7j7ta8og95vb95SMSUHtXJ90xH2wdU4TnGyDD++5CSFbWcIF6r7BPP9jp8NSmizZg76U/3qyYeOlXgtLl1zlY+luDzPg95mp7uriuPbcJo9AidU3As3AM5nP2/lQBeDcSVL3jo8G+CGNB8flpL6+/xykqwpTTpXhXdSpAwB51yI4EWFwPREB4IphlsPIboCDF5trYYXSmvlzVf+enGyxdmc4ZLKC3R2jww/8UDvsFCIHatpD90iSTXMaBGAURpQQe7iuaOTIB3hhPX80iPrOoXITlnani2xYSWgeF/0HcfpNYAmW+nyyZoL1UxG1PUjUVufl6nPli6z4zRC7R7VEU1nKT0fpD9RQWlL9cn8sajxvTyaMOkbh/XdhSLFXC1D3HRva4GkxKXYstvK8fR7ZkdEuOgEcxttMUPPT/dqA7S5Z2/It4cfLjxV1YeFYgxAEgkhP0Htm6XI7pTnRH37Gkct4cZSwWmTMZtyCU0idmd0tS9X3uTIf82QepfcxZbNsdKc=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: letHS5FGTHTEUN26uPGxxj3XVgbrH7pK6XPmFMQWX3CxcwzFUSiQGGFrQO+jE2BdDBfmNEwgbyDe1A1Jn5wt3bIQ2zK1Q0Tpt0gvlpNg/1N0OP+5qqVHyvEHwEA9bniOrXEXgFjGlakvE4agohxc5isjhJ9F3BcK+j0ECUNf2Mmo12zVdK+RAhpqd1+ScNNnSIPe0itjiw6LS36QXi9cb7rUjMYXJu4OwDvzw65ZXaolOhtiTLnJtKrwu5p/u4Cg2Vdf0PBAKFhqKQtTzOp2ssA47/svQc8wgvIMJ5sIrH+jKZZWOfrcZCquW6XlSrm+gp/2p6fSPmwOcLeNY0sJyWM71OMzwwLMbOq3YkKtBgc33BCWBvpkxAzkPXvSesRVkjKiekRAuwzDHnE2QtLwvtQ0duS3WPb8pYqr9RkWZZIHIUZ8h8hEGME8NzVOgU4mQeYJCV1LUh8hpmE7rZ8z1Zuk7ncGCVq1tQkdsBC0Fe45upTatVqle5pAhRvi1KiK7uUm8pjw3zKM0zXM6cU2SlwoviaW4EH1zPQh6pnYSskv3iMdLFVMYyBWqcGy9WM9DkI8hNifUXWbdfoSocYzShDIRLIvrnFBMlZSXJ7R2atzwpz6qzHBoX47JhewRXtToOFWMZt24OALexsd0zB2srGU6EQIlZHOcSuikLMH7bI=
sudo: false
